/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Session
         * @description Whether the cookie in hand is good. The login page asks this on load.
         */
        get: operations["read_session_auth_session_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_auth_session_post"];
        /** Delete Session */
        delete: operations["delete_session_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Batches
         * @description The most recent batches, newest first.
         */
        get: operations["get_batches_batches_get"];
        put?: never;
        /**
         * Submit Batch
         * @description Queue one harvest per category the wishlist names, in the wishlist's order.
         *
         *     The window closes today, so each batch means the same thing when it runs.
         */
        post: operations["submit_batch_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get One Batch */
        get: operations["get_one_batch_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Papers
         * @description Papers with their verdicts, best first; `days` keeps to recent ones.
         */
        get: operations["get_papers_papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssessedOut
         * @description A paper, and its verdict once it has been screened.
         */
        AssessedOut: {
            paper: components["schemas"]["PaperOut"];
            verdict: components["schemas"]["VerdictOut"] | null;
        };
        /**
         * BatchOut
         * @description A batch and how far it has got.
         *
         *     `added` counts papers new to the system; `items` counts every paper the batch
         *     has seen, and `progress` how many wait for each stage or ended in `done` or
         *     `dead`. `state` is the harvest's alone; `status` is the batch's as a whole,
         *     `processing` while its papers are still between stages. `attempts` and
         *     `last_error` describe harvest failures since the last page that succeeded.
         */
        BatchOut: {
            /** Added */
            added: number;
            /** Attempts */
            attempts: number;
            /** Category */
            category: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Items */
            items: number;
            /** Last Error */
            last_error: string | null;
            /** Pages */
            pages: number;
            /** Progress */
            progress: {
                [key: string]: number;
            };
            /**
             * Since
             * Format: date
             */
            since: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "harvesting" | "done" | "failed";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "harvesting" | "processing" | "done" | "failed";
            /**
             * Until
             * Format: date
             */
            until: string;
        };
        /**
         * BatchRequest
         * @description Which papers to pull in: those new or revised on or after a date, in every
         *     category the wishlist names.
         */
        BatchRequest: {
            /**
             * Since
             * Format: date
             */
            since: string;
        };
        /** CriterionOut */
        CriterionOut: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "want" | "dealbreaker";
            /** Requirement */
            requirement: string;
            /** Weight */
            weight: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description What `/health` reports. `ok` is false when the database is unreachable.
         */
        HealthResponse: {
            /** Database */
            database: boolean;
            /** Ok */
            ok: boolean;
            /**
             * Revision
             * @description Migration the database is on, null if never migrated
             */
            revision?: string | null;
        };
        /** PaperOut */
        PaperOut: {
            /** Abstract */
            abstract: string;
            /** Arxiv Id */
            arxiv_id: string;
            /** Authors */
            authors: string[];
            /** Categories */
            categories: string[];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Title */
            title: string;
        };
        /** PaperPage */
        PaperPage: {
            /** Items */
            items: components["schemas"]["AssessedOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * ProfileOut
         * @description The wishlist papers are ranked against, and the thresholds applied to it.
         */
        ProfileOut: {
            /** Categories */
            categories: string[];
            /** Criteria */
            criteria: components["schemas"]["CriterionOut"][];
            /** Dealbreaker Threshold */
            dealbreaker_threshold: number;
            /** Merit Weight */
            merit_weight: number;
            /** Name */
            name: string;
            /** Screen Threshold */
            screen_threshold: number;
        };
        /**
         * SessionStatus
         * @description Whether the caller is signed in, and whether signing in is even possible.
         *
         *     `configured` is false when the deployment has no passphrase hash, so the
         *     login page can say that rather than blame the phrase you typed.
         */
        SessionStatus: {
            /** Authenticated */
            authenticated: boolean;
            /** Configured */
            configured: boolean;
        };
        /**
         * SignIn
         * @description The one credential there is.
         */
        SignIn: {
            /** Passphrase */
            passphrase: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerdictOut
         * @description Where a paper stands against the wishlist.
         *
         *     `stage` is `screen` when only the abstract was judged — `merit` is then null
         *     and `total` is fit alone — and `full` once the text was. The two totals are
         *     not on one scale. `per_criterion` holds each research interest's position on
         *     its levels, from 0 to 1: an ordering, not a percentage.
         */
        VerdictOut: {
            /** Blocked By */
            blocked_by: string[];
            /** Eligible */
            eligible: boolean;
            /** Fit */
            fit: number;
            /** Merit */
            merit: number | null;
            /** Needs Review */
            needs_review: boolean;
            /** Notes */
            notes: string[];
            /** Per Criterion */
            per_criterion: {
                [key: string]: number;
            };
            /**
             * Stage
             * @enum {string}
             */
            stage: "screen" | "full";
            /** Total */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_session_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatus"];
                };
            };
        };
    };
    create_session_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_auth_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_batches_batches_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_batch_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_one_batch_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_papers_papers_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Published within this many days */
                days?: number | null;
                order?: "rank" | "newest";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
}
